# Default profile (local run)
# Uses in-memory H2 by Spring Boot defaults unless overridden.

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dapoet}
cloudinary.api-key=${CLOUDINARY_API_KEY:837136456483266}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:kgqWQ-Zhhr2EQUJSftyPAKbC9hc}
