# Local profile (H2)
spring.datasource.url=jdbc:h2:mem:legendcoffee
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud-name=dapoet
cloudinary.api-key=837136456483266
cloudinary.api-secret=kgqWQ-Zhhr2EQUJSftyPAKbC9hc

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luanninh2005@gmail.com
spring.mail.password=mjtj mzzs czpy fdmb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html