# Production profile (Microsoft SQL Server)
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=legendcoffee;encrypt=true;trustServerCertificate=true}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud-name=dapoet
cloudinary.api-key=837136456483266
cloudinary.api-secret=kgqWQ-Zhhr2EQUJSftyPAKbC9hc